version: '3'

networks:
    laravel:

services:
    dnsmasq_laravel:
        restart: always
        image: strm/dnsmasq
        container_name: dnsmasq_laravel
        volumes:
            - ./docker/dnsmasq/dnsmasq.conf:/etc/dnsmasq.conf
        ports:
            - "53:53/udp"
        cap_add:
            - NET_ADMIN
        networks:
            - laravel

    nginx_laravel:
        build:
            context: .
            dockerfile: ./docker/nginx.dockerfile
        container_name: nginx_laravel
        env_file:
            - ./docker/.env
        ports:
            - "80:80"
        volumes:
            - ./:/var/www/html:delegated
            - ./docker/nginx/templates:/etc/nginx/templates
        depends_on:
            - php_laravel
            - mysql_laravel
        networks:
            - laravel

    mysql_laravel:
        image: mysql:5.7.16
        container_name: mysql_laravel
        env_file:
            - ./docker/.env
        restart: unless-stopped
        tty: true
        ports:
            - "3306:3306"
        volumes:
            - ./docker/mysql:/var/lib/mysql:delegated
        environment:
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql_laravel
        networks:
            - laravel

    php_laravel:
        build:
            context: .
            dockerfile: ./docker/php.dockerfile
        container_name: php_laravel
        volumes:
            - ./:/var/www/html:delegated
        ports:
            - "9000:9000"
        networks:
            - laravel

    composer:
        build:
            context: .
            dockerfile: ./docker/composer.dockerfile
        container_name: composer
        volumes:
            - ./:/var/www/html:delegated
        working_dir: /var/www/html
        depends_on:
            - php_laravel
        user: laravel
        entrypoint: ['composer', '--ignore-platform-reqs']
        networks:
            - laravel

    npm:
        image: node:14.16
        env_file:
            - ./docker/.env
        container_name: npm
        volumes:
            - ./:/var/www/html:delegated
        working_dir: /var/www/html
        entrypoint: ['npm']
        networks:
            - laravel

    cypress:
        image: "cypress/included:6.6.0"
        container_name: cypress
        depends_on:
            - nginx_laravel
        environment:
            - CYPRESS_baseUrl=http://host.docker.internal
        working_dir: /e2e
        # entrypoint: ['cypress']
        volumes:
            - ./:/e2e
        networks:
            - laravel

    artisan:
        build:
            context: .
            dockerfile: ./docker/php.dockerfile
        container_name: artisan
        volumes:
            - ./:/var/www/html:delegated
        depends_on:
            - mysql_laravel
        working_dir: /var/www/html
        entrypoint: ['php', '/var/www/html/artisan']
        networks:
            - laravel